# Generated by Django 6.0.2 on 2026-02-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100, verbose_name='Nom')),
                ('rx_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP RX (écoute)')),
                ('rx_port', models.PositiveIntegerField(default=9000, verbose_name='Port RX')),
                ('auto_start', models.BooleanField(default=False, verbose_name='Auto-start')),
                ('show_unmapped', models.BooleanField(default=False, verbose_name='Show unmapped logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration OSC',
                'verbose_name_plural': 'Configurations OSC',
            },
        ),
        migrations.CreateModel(
            name='OSCDispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osc_input', models.CharField(max_length=255, verbose_name='Adresse OSC (entrée)')),
                ('osc_output', models.CharField(max_length=255, verbose_name='Adresse OSC (sortie)')),
                ('tx_ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP destination')),
                ('tx_port', models.PositiveIntegerField(default=9000, verbose_name='Port destination')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatchers', to='converter.oscconfig')),
            ],
            options={
                'verbose_name': 'Dispatcher OSC',
                'verbose_name_plural': 'Dispatchers OSC',
                'ordering': ['osc_input'],
            },
        ),
    ]
